server:
  port: 9002
spring:
  application:
    name: aggregation
  profiles:
    include: dev
  data:
    mongodb:
      database:
      username:
      password:
      host: 192.168.3.4
      port: 27017
knife4j:
  enable: true
  setting:
    language: zh_cn
  #开启生产环境屏蔽
  production: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hidewnd.costing.controller

jx3-api:
  token: ''
  ticket: ''