server:
  port: 9002
spring:
  application:
    name: winds-application
  profiles:
    include: dev
  cache:
    live-time: 180000
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: 192.168.3.62
      port: 6379
      database: 4
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-wait: -1ms
          max-active: 6
    mongodb:
      database: winds_jx3
      host: 192.168.3.62
      port: 27017
      authentication-database: admin
      username: admin
      password: pwd

knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan:
        - com.hidewnd.winds.costing.controller
        - com.hidewnd.winds.aggregation.controller

box:
  default:
    server: 剑胆琴心

jx3api:
  url: https://www.jx3api.com
  token: ''
  ticket: ''
